### ISSUE TITLE
Add license (?)

### ISSUE THREAD

**Issue by petterbejo** [Dedward5/motorsportdatalogger#55]
Hi David, think that the easiest is to reach out to you this way :) I found your data logger when looking for a way of collecting real-time data from my car with a Raspberry Pi but without OBD. You don't provide a license, and Github only permits using a forked repo that does not provide any license within Github (section D5 in the terms of service), so I thought I'd reach out to you to ask for permission. So basically my question is if I can fork the repo and use/change the code for personal (not commercial) use and/or if you could provide a license?  If you're still using the code/working on it, I'd also like to contribute to it...Thanks a lot in advance....

**Comment by Dedward5** [comment]
Hi, I think I added a licence successfully. Im happy for you to fork and do what you want with this as it was just a bit of fun for me and iv not done anything with it for ages. I hope it serves a good foundation for your project.

**Comment by petterbejo** [comment]
Great, thanks a lot, I really appreciate it!
